# fly.toml app configuration file generated for jatu-server-long-cloud-6971 on 2025-09-17T17:58:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jatu-server-long-cloud-6971'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
