"use strict";
const ProductsRoutes = require("../../app/products/router.js");
const ServicesRoutes = require("../../app/services/router.js");
const BlogRoutes = require("../../app/blog/router.js");
const SliderRoutes = require("../../app/slider/router.js");
const CategoryRoutes = require("../../app/categories/router.js");
const CountriesRoutes = require("../../app/countries/router.js");
const SizesRoutes = require("../../app/sizes/router.js");
const SubCategoryRoutes = require("../../app/subcategories/router.js");
const BrandsRoutes = require("../../app/brands/router.js");

const UsersRoutes = require("../../app/users/router.js");
const EmailRoutes = require("../../app/emails/router.js");
const PagesRoutes = require("../../app/pages/router.js");
const SeoRoutes = require("../../app/seo/router.js");
const OrderRoutes = require("../../app/order/router.js");
const ProjectRoutes = require("../../app/projects/router.js");
const CostItemsRoutes = require("../../app/cost-items/router.js");
const CostDefinitionRoutes = require("../../app/project-cost/router.js");
const ProjectZonesRoutes = require("../../app/project-zones/router.js");
const ProjectRequestRoutes = require("../../app/project-requests/router.js");
const RegionsRoutes = require("../../app/regions/router.js");
const MarketWatchRoutes = require("../../app/market-watch/router.js");
const InternationalWatchRoutes = require("../../app/international-watch/router.js");
const SeasonsRoutes = require("../../app/seasons/router.js");
const UnitSetupRoutes = require("../../app/unit-setup/router.js");
const FarmOwnersRoutes = require("../../app/farm-owners/router.js");
const AgriInvestorsRoutes = require("../../app/agri-investors/router.js");
const ExpertRoutes = require("../../app/experts/router.js");
const FarmsRegisterRoutes = require("../../app/farms-register/router.js");
const RequestedFarmsRoutes = require("../../app/requested-farms/router.js");
const AvailableFarmsRoutes = require("../../app/available-farms/router.js");
const MeetingRequestRoutes = require("../../app/meetings/router.js");
const UpcomingEventsRoutes = require("../../app/upcoming-events/router.js");
const NewsletterRoutes = require("../../app/newsletter/router.js");
const ProjectCategoriesRoutes = require("../../app/project-categories/router.js");
const FarmApplicationRoutes = require("../../app/farm-application/router.js");
const ListedEquipmentsRoutes = require("../../app/farm-equipments/router.js");
const EqApplicationsRoutes = require("../../app/equipment-application/router.js");

module.exports = function (app) {
  app.use("/api/emails", EmailRoutes);
  app.use("/api/products", ProductsRoutes);
  app.use("/api/services", ServicesRoutes);
  app.use("/api/blog", BlogRoutes);
  app.use("/api/slider", SliderRoutes);
  app.use("/api/categories", CategoryRoutes);
  app.use("/api/countries", CountriesRoutes);
  app.use("/api/sizes", SizesRoutes);
  app.use("/api/brands", BrandsRoutes);
  app.use("/api/subcategories", SubCategoryRoutes);
  // users
  
  app.use("/api/users", UsersRoutes);
  app.use("/api/pages", PagesRoutes);
  app.use("/api/seo", SeoRoutes);
  app.use("/api/order", OrderRoutes);
  app.use("/api/projects", ProjectRoutes);
  app.use("/api/project/cost", CostItemsRoutes);
  app.use("/api/project/zones", ProjectZonesRoutes);
  app.use("/api/cost/definition", CostDefinitionRoutes);
  app.use("/api/project/request", ProjectRequestRoutes);
  app.use("/api/regions", RegionsRoutes);
  app.use("/api/market/watch", MarketWatchRoutes);
  app.use("/api/international/market/watch", InternationalWatchRoutes);
  app.use("/api/seasons", SeasonsRoutes);
  app.use("/api/unit/setup", UnitSetupRoutes);
  app.use("/api/farm/owners", FarmOwnersRoutes);
  app.use("/api/agri/investors", AgriInvestorsRoutes);
  app.use("/api/experts", ExpertRoutes);
  app.use("/api/farms/register", FarmsRegisterRoutes);
  app.use("/api/requested/farms", RequestedFarmsRoutes);
  app.use("/api/available/farms", AvailableFarmsRoutes);
  app.use("/api/meetings/request", MeetingRequestRoutes);
  app.use("/api/upcoming/events", UpcomingEventsRoutes);
  app.use("/api/newsletter", NewsletterRoutes);
  app.use("/api/farmlands-application", FarmApplicationRoutes);
  app.use("/api/list-equipment", ListedEquipmentsRoutes);
  app.use("/api/equipment-applications", EqApplicationsRoutes);
  //new
  
  app.use("/api/project-categories", ProjectCategoriesRoutes);
};
